project: "CMF-DEQ"
run_name: "baseline"

data:
  path: '/content/drive/MyDrive/Colab Notebooks/CsmPower5.h5'
  num_workers: 1
training:
  epochs: 50
  training_batch_size: 32
  valid_batch_size: 5
  test_batch_size: 5
  learning_rate: 1e-5
  stepsize: [1.0]
  sigma_denoiser: [0.3]

model:
  frequency: 4.2e6
  max_iter: 20

wandb:
  enabled: true

save_path: "results"
